apiversion: v1beta
kind: TemplateBlock
metadata:
  labels:
  - pavedroad
  - microservice
  - integration
  - sonarcloud
  - dev-env
  tags:
  - pavedroad
  - microservice
  - integration
  - sonarcloud
  - dev-env
  information:
    description: 
    title: Sonarlcoud configuration generator
    contact:
      author: John Scharber
      organization: PavedRoad
      email: support@pavedroad.io
      website: www.pavedroad.io
      support: pavedroad-io.slack.com
id: cache://io.pavedroard.blocks/microservice/development-tools
family: pavedroad/microservice/blocks/manifests
baseDirectory: /microservice/integrations/sonarcloud
usagerights:
  termsofservice: As is
  licenses: Apache 2
  contributelink: ""
  accesstoken: ""
imports: []
baseDirectory: io.pavedroard.blocks/microservice/integrations/sonarcloud
homeDirectory: .
templateMap:
  - fileName: sonar-project.properties.tpl
    description: Sonarcloud configuration
    templateFunction: sonarCloudFunctoinMap()
    outputFileName: sonsonar-project.properties
    outputType: OutputFile
templateExports:
  - templateVar: "{{.Info.Name}}"
  - templateVar: "{{.Info.Organization}}"
  - templateVar: "{{.Info.Version}}"
  - templateVar: "{{.SonarLogin}}"
