
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 

bases:
  - kafka
  - db
  - films

resources:
  - namespace.yaml

commonLabels:
  pavedroad.env: dev

commonAnnotations:
  pavedroad.kustomize.base: films/manifests/kubernetes/dev
  pavedroad.kustomize.bases: "films,db"
