apiversion: v1beta
kind: DockerBlock
metadata:
  labels:
  - pavedroad
  - docker
  - dockerfile
  - microservice
  - dev
  tags:
  - pavedroad
  - docker
  - dockerfile
  - microservice
  - dev
  information:
    description: Generate Dockerfile for a microservice
    title: Dockerfile generator
    contact:
      author: John Scharber
      organization: PavedRoad
      email: support@pavedroad.io
      website: www.pavedroad.io
      support: pavedroad-io.slack.com
id: cache://io.pavedroad.blocks/microservice/manifests/docker/dockerfile.yaml
family: pavedroad/microservice/blocks/manifests/docker
usagerights:
  termsofservice: As is
  licenses: Apache 2
  contributelink: ""
  accesstoken: ""
imports: []
baseDirectory: io.pavedroad.blocks/microservice/manifests/docker
homeDirectory: manifests
homeFilename: Dockerfile
templateMap:
  - fileName: dockerfile.tpl
    description: Dockerfile for building a container
    templateFunction: stringFunctionMap()
templateExports:
  - templateVar: "{{.Info.Name}}"
  - templateVar: "{{.Info.Organization}}"
  - templateVar: "{{.Info.GitHubOrg}}"
  - templateVar: "{{.Info.Version}}"
  - templateVar: "{{.Project.Description}}"
  - templateVar: "{{.Info.ID}}"
  - templateVar: "{{.DefinitionFile}}"
