{{define "manifests/kubernetes/dev/template/template-deployment.yaml"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      pavedroad.service: {{.Name}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pavedroad.service: {{.Name}}
    spec:
      containers:
      - image: localhost:32000/{{.Organization}}/{{.Name}}:0.0
        env:
        - name: HTTP_IP_ADDR
          valueFrom:
            configMapKeyRef:
              name: {{.Name}}-configmap
              key: ip
        - name: HTTP_IP_PORT
          valueFrom:
            configMapKeyRef:
              name: {{.Name}}-configmap
              key: port
        name: {{.Name}}
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
