{{define "manifests/kubernetes/dev/template/template-service.yaml"}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    pavedroad.service: {{.Name}}
  type: NodePort
status:
  loadBalancer: {}
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
