
resources:
  - httpcollector-deployment.yaml
  - httpcollector-service.yaml

commonLabels:
  pavedroad.service: httpcollector

commonAnnotations:
  pavedroad.roadctl.version: alphav1
  pavedroad.roadctl.web: www.pavedroad.io
  pavedroad.roadctl.support: support@pavedroad.io

configMapGenerator:
- name: httpcollector-configmap
  literals:
  - ip=0.0.0.0
  - port=8081
