apiversion: v1beta
kind: CompositeBlock
metadata:
  labels:
  - pavedroad
  - microservice
  - development-tools
  - cockroach-tools
  - kubernetes-tools
  - dev-env
  tags:
  - pavedroad
  - microservice
  - development-tools
  - cockroach-tools
  - kubernetes-tools
  - pavedroad-tools
  - microk8s-tools
  - sql-tools
  - dev-env
  information:
    description: 
    title: Tools for working with microservice and kubernetes
    contact:
      author: John Scharber
      organization: PavedRoad
      email: support@pavedroad.io
      website: www.pavedroad.io
      support: pavedroad-io.slack.com
id: cache://io.pavedroard.blocks/microservice/development-tools
family: pavedroad/microservice/blocks/manifests
baseDirectory: /microservice/development-tools
usagerights:
  termsofservice: As is
  licenses: Apache 2
  contributelink: ""
  accesstoken: ""
imports: []
importedBlocks:
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - pavedroad
    - microservice
    - development-tools
    - microk8s-tools
    - dev-env
  id: cache://io.pavedroard.blocks/microservice/development-tools/microk8s/microk8s.yaml
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - pavedroad
    - microservice
    - pavedroad-tools
    - dev-env
  id: cache://io.pavedroard.blocks/microservice/development-tools/pavedroad/pavedroad.yaml
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - pavedroad
    - microservice
    - kubernetes-tools
    - dev-env
  id: cache://io.pavedroard.blocks/microservice/development-tools/kubernetes/kubernetes.yaml
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - pavedroad
    - microservice
    - rest-api-tools
    - dev-env
  id: cache://io.pavedroard.blocks/microservice/development-tools/rest/rest.yaml
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - pavedroad
    - microservice
    - sql-api-tools
    - dev-env
  id: cache://io.pavedroard.blocks/microservice/development-tools/sql/sql.yaml
