{{define "manifests/docker-db-only.yaml"}}
version: '3'

services:
  roach-ui:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    ports:
     - "26257:26257"
     - "6060:8080"
    volumes:
     - /tmp/volumes/data/db-1:/cockroach/cockroach-data
{{/* vim: set filetype=gotexttmpl: */ -}}{{end}}
