{{define "manifests/docker-compose.yaml"}}
version: '3'

services:
  {{.Name}}:
    image: {{.GitHubOrg}}/{{.Name}}
    expose:
     - "8081"
    ports: 
     - 8081:8081
    environment:
     - HTTP_IP_ADDR=0.0.0.0
     - HTTP_IP_PORT=8081
     - APP_DB_IP=manifests_roach-ui_1
     - PRLOG_AUTOINIT=true
     - PRLOG_CFGTYPE=env
     - PRLOG_ENABLEKAFKA=true
     - PRLOG_FILEFORMAT=text
     - PRLOG_FILELOCATION=logs/{{.Name}}.log
     - PRKAFKA_BROKERS=kafka:9092
    depends_on:
     - kafka
  roach-ui:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    expose:
     - "8080"
     - "26257"
    ports:
     - "26257:26257"
     - "6060:8080"
    volumes:
     - "${ROACH_VOLUME_DIR}/data/db-1:/cockroach/cockroach-data"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9093
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: logs:1:1
{{/* vim: set filetype=gotexttmpl: */ -}}{{end}}
