{{define "manifests/skaffold.yaml"}}
apiVersion: skaffold/v1beta9
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  artifacts:
  - image: localhost:32000/{{.Organization}}/{{.Name}}
    context: .
    docker:
      dockerfile: manifests/Dockerfile
  - image: localhost:32000/{{.Organization}}/{{.Name}}initdb
    context: .
    docker:
      dockerfile: manifests/InitDbDockerFile
deploy:
  kustomize:
    path: "manifests/kubernetes/dev"
{{/* vim: set filetype=gotexttmpl: */ -}}{{end}}
