{{define "skaffold.yaml"}}
apiVersion: skaffold/v1beta9
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  artifacts:
  - image: localhost:32000/{{.Organization}}/{{.Name}}
    context: .
    docker:
      dockerfile: manifests/Dockerfile
  - image: localhost:32000/{{.Organization}}/{{.Name}}initdb
    context: .
    docker:
      dockerfile: manifests/InitDbDockerFile
deploy:
  kubectl:
    manifests:
    - manifests/kubernetes/{{.Name}}-deployment.yaml
    - manifests/kubernetes/{{.Name}}-service.yaml
    - manifests/kubernetes/roach-ui-claim0-persistentvolumeclaim.yaml
    - manifests/kubernetes/roach-ui-deployment.yaml
    - manifests/kubernetes/roach-ui-service.yaml
{{end}}
