{{define "manifests/skaffold.yaml"}}
apiVersion: skaffold/v1beta9
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  artifacts:
  - image: localhost:32000/{{.Organization}}/{{.Name}}
	  custom:
    dependencies:
    	paths:
      	- "**.go"
  - image: localhost:32000/{{.Organization}}/{{.Name}}initdb
    context: .
    docker:
      dockerfile: manifests/InitDbDockerFile
deploy:
  kustomize:
    paths:
    - "manifests/kubernetes/dev"

profiles:
  - name: dev-debug
		activation:
			- env: GODEBUG=true
    deploy:
      kustomize:
        paths:
        - "manifests/kubernetes/dev-debug"
{{/* vim: set filetype=gotexttmpl: */ -}}{{end}}
