{{ define "manifests/kubernetes/stag/kustomization.yaml"}}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{.Namespace}}

bases:
  - {{.Name}}
  - ingress

commonLabels:
  pavedroad.env: staging

commonAnnotations:
  pavedroad.kustomize.base: {{.Name}}/manifests/kubernetes/stag
  pavedroad.kustomize.bases: "{{.Name}}"
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
