
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- kafka
- eventcollector

resources:
- namespace.yaml

commonLabels:
  pavedroad.env: dev

commonAnnotations:
  pavedroad.kustomize.base: eventcollector/manifests/kubernetes/dev
  pavedroad.kustomize.bases: eventcollector,kafka

