
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mirantis

bases:
- kafka
- httpcollector

resources:
- namespace.yaml

commonLabels:
  pavedroad.env: dev

commonAnnotations:
  pavedroad.kustomize.base: httpcollector/manifests/kubernetes/dev
  pavedroad.kustomize.bases: httpcollector,kafka
