
apiVersion: skaffold/v1beta9
kind: Config
build:
  insecureRegistries:
    - localhost:32000
  artifacts:
  - image: localhost:32000/acme-demo/films
    context: .
    docker:
      dockerfile: manifests/Dockerfile
  - image: localhost:32000/acme-demo/filmsinitdb
    context: .
    docker:
      dockerfile: manifests/InitDbDockerFile
deploy:
  kustomize:
    path: "manifests/kubernetes/dev"
