
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbridge
  labels:
    env: dev-debug
spec:
  template:
    spec:
      containers:
        - name: eventbridge
          env:
           - name: GODEBUG
             value: true
