{{define "roach-ui-claim0-persistentvolumeclaim.yaml"}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    pavedroad.service: roach-ui-claim0
  name: roach-ui-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
{{end}}
