{{define "template-deployment.yaml"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    roadctlVersion: alphav1
    pavedroad: www.pavedroad.io
  creationTimestamp: null
  labels:
    pavedroad.service: {{.Name}}
  name: {{.Name}}
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      pavedroad.service: {{.Name}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pavedroad.service: {{.Name}}
    spec:
      containers:
      - image: localhost:32000/acme/{{.Name}}:0.0
        env:
        - name: HTTP_IP_ADDR
          value: "0.0.0.0"
        - name: HTTP_IP_PORT
          value: "8081"
        - name: APP_DB_IP
          value: "roach-ui"
        name: {{.Name}}
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
{{end}}
