{{define "template-service.yaml"}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    roadctlVersion: alphav1
    pavedroad: www.pavedroad.io
  creationTimestamp: null
  labels:
    pavedroad.service: {{.Name}}
  name: {{.Name}}
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    pavedroad.service: {{.Name}}
  type: NodePort
status:
  loadBalancer: {}
{{end}}
