
apiVersion: v1
kind: Service
metadata:
  name: eventbridge
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    pavedroad.service: eventbridge
  type: NodePort
status:
  loadBalancer: {}
