apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-11-27T21:42:38Z"
  labels:
    run: debug
  name: debug
  namespace: default
  resourceVersion: "1084286"
  selfLink: /api/v1/namespaces/default/pods/debug
  uid: 32c8ab83-2be3-4241-95ca-836aa7e633bb
spec:
  containers:
  - image: localhost:32000/acme/filmsinitdb:v0.0alpha-dirty
    env:
    - name: COCKROACH_HOST
      value: "roach-ui"
    imagePullPolicy: Always
    name: debug
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-98gh4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-98gh4
    secret:
      defaultMode: 420
      secretName: default-token-98gh4
status:
  phase: Pending
  qosClass: BestEffort
