apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sql
  name: sql
spec:
  containers:
  - image: pavedroadio/cockroachdb-client:0.3
    name: sql
    terminationMessagePath: "/tmp/sql-log"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
