{{ define "manifests/kubernetes/stag/template/template-deployment.yaml"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
spec:
  replicas: 3
  strategy: {}
  selector:
    matchLabels:
      pavedroad.service: {{.Name}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        pavedroad.service: {{.Name}}
    spec:
      containers:
      - image: 400276217548.dkr.ecr.us-west-1.amazonaws.com/io.pavedroad.staging/{{.Name}}
        env:
        - name: PRLOG_AUTOINIT
          value: "true"
        - name: PRLOG_CFGTYPE
          value: "env"
        - name: PRLOG_ENABLEKAFKA
          value: "false"
        - name: PRLOG_FILEFORMAT
          value: "text"
        - name: PRLOG_FILELOCATION
          value: "logs/{{.Name}}.log"
        - name: PRKAFKA_BROKERS
          value: "kafka:9092"
        - name: PR_BACKEND_END
          value: "prod"
        - name: HTTP_IP_ADDR
          valueFrom:
            configMapKeyRef:
              name: {{.Name}}-configmap
              key: ip
        - name: HTTP_IP_PORT
          valueFrom:
            configMapKeyRef:
              name: {{.Name}}-configmap
              key: port
        name: {{.Name}}
        ports:
        - containerPort: {{.HTTPPort}}
        resources: {}
      restartPolicy: Always
status: {}
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
