{{ define "manifests/kubernetes/stag/template/template-service.yaml"}}

apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
spec:
  ports:
  - name: "{{.HTTPPort}}"
    port: {{.HTTPPort}}
    targetPort: {{.HTTPPort}}
  selector:
    pavedroad.service: {{.Name}}
  type: NodePort
status:
  loadBalancer: {}
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
