{{define "manifests/kubernetes/dev/kafka/kustomization.yaml"}}
resources:
  - roach-ui-claim0-persistentvolumeclaim.yaml
  - roach-ui-deployment.yaml
  - roach-ui-service.yaml

configMapGenerator:
- name: cockroach-configmap
  literals:
  - host-ip=roach-ui
{{end}}
