{{ define "manifests/kubernetes/dev/kustomization.yaml"}}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{.Namespace}}

bases:
- kafka
- {{.Name}}

resources:
- namespace.yaml

commonLabels:
  pavedroad.env: dev

commonAnnotations:
  pavedroad.kustomize.base: {{.Name}}/manifests/kubernetes/dev
  pavedroad.kustomize.bases: {{.Name}},kafka
{{end}}{/* vim: set filetype=gotexttmpl: */ -}}
