{{define "manifests/docker-compose.yaml"}}
version: '3'

services:
  {{.Name}}:
    image: {{.Organization}}/{{.Name}}
    expose:
     - "{{.HTTPPort}}"
    ports: 
     - {{.HTTPPort}}:{{.HTTPPort}}
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
      KAFKA_ZOOKEEPER_CONNECT: "${DOCKER_IP}:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
