{{define "manifests/docker-compose.yaml"}}
version: '3'

services:
  {{.Name}}:
    image: {{.Organization}}/{{.Name}}
    expose:
     - "8081"
    ports: 
     - 8081:8081
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
