{{define "manifests/skaffold.yaml"}}
apiVersion: skaffold/v2beta10
kind: Config
build:
  insecureRegistries:
  - localhost:32000
  artifacts:
  - image: localhost:32000/{{.GitHubOrg}}/{{.Name}}
    context: .
    docker:
      dockerfile: manifests/Dockerfile
deploy:
  kustomize:
    paths:
    - "manifests/kubernetes/dev"
profiles:
  - name: dev-debug
    activation:
    - env: GODEBUG=true
    deploy:
      kustomize:
        paths:
        - "manifests/kubernetes/dev-debug"
  - name: staging
    build:
      artifacts:
      - image: 400276217548.dkr.ecr.us-west-1.amazonaws.com/io.pavedroad.staging/{{.Name}}
        context: .
        docker:
          dockerfile: manifests/Dockerfile
    deploy:
      kustomize:
        paths:
        - "manifests/kubernetes/stag"
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
