{{define "manifests/kubernetes/dev/db/roach-ui-claim0-persistentvolumeclaim.yaml"}}
apiVersion: v1
kind: PersistentVolumeClaim
  name: roach-ui-claim0
  labels:
    pavedroad.service: roach-ui-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
{{end}}
