apiversion: v1beta
kind: KustomizeBlock
metadata:
  labels:
  - pavedroad
  - skaffold
  - kubernetes
  - kustomize
  - microservice
  - dev
  - dev-debug
  - db
  - cockroach
  - ms-packager
  tags:
  - pavedroad
  - skaffold
  - kubernetes
  - kustomize
  - microservice
  - db
  - cockroach
  - dev
  - dev-debug
  - ms-packager
  information:
    description: Deploys cockroack db to k8s cluster
    title: Deploys cockroack db to k8s cluster
    contact:
      author: John Scharber
      organization: PavedRoad
      email: support@pavedroad.io
      website: www.pavedroad.io
      support: pavedroad-io.slack.com
id: cache://io.pavedroard.blocks/microservice/manifests/kubernetes/cockroach.yaml
family: pavedroad/microservice/blocks/manifests/kubernetes
usagerights:
  termsofservice: As is
  licenses: Apache 2
  contributelink: ""
  accesstoken: ""
imports: []
baseDirectory: io.pavedroard.blocks/microservice/manifests/kubernetes/cockroach

homeDirectory: manifests/kubernetes/dev/cockroach
templateMap:
  - fileName: kustomization.tpl
    outputFileName: kustomization.yaml
    outputType: OutputFile
    description: Kustomize file for cockroachdb
    templateFunction: stringFunctionMap()
  - fileName: roach-ui-claim0-persistentvolumeclaim.tpl
    outputFileName: roach-ui-claim0-persistentvolumeclaim.yaml
    outputType: OutputFile
    description: PV for coackroach storage
    templateFunction: stringFunctionMap()
  - fileName: roach-ui-deployment.tpl
    outputFileName: roach-ui-deployment.yaml
    outputType: OutputFile
    description: k8s deployment for cockroachdb
    templateFunction: stringFunctionMap()
  - fileName: roach-ui-service.tpl
    outputFileName: roach-ui-service.yaml
    outputType: OutputFile
    description: k8s service for cockroachdb
    templateFunction: stringFunctionMap()
