apiversion: v1beta
kind: KustomizeBlock
metadata:
  labels:
  - pavedroad
  - skaffold
  - kubernetes
  - kustomize
  - microservice
  - dev-debug
  tags:
  - pavedroad
  - skaffold
  - kubernetes
  - kustomize
  - microservice
  - dev-debug
  information:
    description: Generate skaffold.yaml configuration file
    title: Generate skaffold.yaml configuration file
    contact:
      author: John Scharber
      organization: PavedRoad
      email: support@pavedroad.io
      website: www.pavedroad.io
      support: pavedroad-io.slack.com
id: cache://io.pavedroard.blocks/microservice/manifests/kubernetes/kustomize-dev-debug.yaml
family: pavedroad/microservice/blocks/manifests/kubernetes
usagerights:
  termsofservice: As is
  licenses: Apache 2
  contributelink: ""
  accesstoken: ""
imports: []
baseDirectory: io.pavedroard.blocks/microservice/manifests/kubernetes/
homeDirectory: manifests
templateMap:
  - fileName: kustomization-debug.tpl
    outputFileName: kustomization.yaml
    outputType: OutputFile
    description: Top level kustomize configuration for development environment
    templateFunction: stringFunctionMap()
templateExports:
  - templateVar: "{{.Info.Name}}"
  - templateVar: "{{.Project.KubeConfig.Namespace}}"
importedBlocks:
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - kubernetes
    - kafka
    - zookepper
    - kubernetes
    - kustomize
    - envconfiguration
    - microservice
    - dev
    - kafka
  id: cache://io.pavedroard.blocks/microservice/manifests/kubernetes/kafka.yaml
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - kubernetes
    - kafka
    - zookepper
    - kubernetes
    - kustomize
    - envconfiguration
    - microservice
    - dev
    - cockroach
  id: cache://io.pavedroard.blocks/microservice/manifests/kubernetes/cockroach.yaml
- apiversion: ""
  kind: ""
  metadata:
    labels:
    - kubernetes
    - kafka
    - zookepper
    - kubernetes
    - kustomize
    - envconfiguration
    - microservice
    - dev
    - ms-packager
  id: cache://io.pavedroard.blocks/microservice/manifests/kubernetes/microservice.yaml
