{{ define "manifests/kubernetes/stag/ingress/rproxy.yaml"}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eo-{{.Name}}-reverse-proxy
  namespace: pavedroad
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.pavedroad.io
    http:
      paths:
      - path: /api/v1/namespace/{{.Namespace}}/{{.Name}}
        pathType: Prefix
        backend:
          service:
            name: {{.Name}}
            port:
              number: 8082
      - path: /api/v1/namespace/{{.Namespace}}/{{.Name}}LIST
        pathType: Prefix
        backend:
          service:
            name: {{.Name}}
            port:
              number: 8082
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
