{{ define "manifests/kubernetes/stag/db/stagging-db-service.yaml"}}
apiVersion: v1
kind: Service
metadata:
  labels:
    pavedraod.service: stagging-db
  name: stagging-db
spec:
  ports:
  - name: "26257"
    port: 26257
    targetPort: 26257
  - name: "6060"
    port: 6060
    targetPort: 8080
  selector:
    pavedroad.service: stagging-db
status:
  loadBalancer: {}
{{end}}{{/* vim: set filetype=gotexttmpl: */ -}}
