
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pavedroad

bases:
- kafka
- eventbridge

resources:
- namespace.yaml

commonLabels:
  pavedroad.env: dev

commonAnnotations:
  pavedroad.kustomize.base: eventbridge/manifests/kubernetes/dev
  pavedroad.kustomize.bases: eventbridge,kafka
